### ISSUE TITLE
Missed github.io link in transition to Infineon

### ISSUE THREAD

**Issue by morser499** [cypresssemiconductorco/cypresssemiconductorco.github.io#2]
**Prerequisites**

Can you reproduce the problem reliably?
Yes

Did you check current release notes for known issues?
Yes

If this is not the latest release, have you checked newer releases? 
NA

**Description**:

The following github.io links do not direct to infineon github:
https://cypresssemiconductorco.github.io/TARGET_CY8CPROTO-064B0S1-SSA/html/modules.html
https://cypresssemiconductorco.github.io/TARGET_CY8CKIT-062S4/html/modules.html

**Steps to Reproduce:**

1. Open either link above

**Expected Result:**
The doxygen documentation is available.

**Actual Result:**
An error page telling me to file a ticket here is displayed.

**Frequency (1/1, 1/50, 1/100):**
1/1

**Comment by vmedcy** [comment]
@cy-msur added the necessary redirect links:

https://github.com/cypresssemiconductorco/cypresssemiconductorco.github.io/commit/8b0b58249ea434c191f554b7e290ce33a8968415

Now the links are operational.
